name: Backend CI/CD

on:
    push:
        branches: [main]

jobs:
    build-and-push:
        name: build and push docker image to ghcr
        permissions:
            packages: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
    
            - name: Check for changed files in backend
              id: backend_changes
              run: |
                changed_files=$(git diff --name-only HEAD~1 HEAD | grep -E '^(backend)/src' | xargs)
                if [ -z "$changed_files" ]; then
                    echo "No changes in backend/src directories."
                else
                    echo "Changes detected in backend/src directories, rebuilding the image"
                    echo "changed_files=$changed_files" >> $GITHUB_OUTPUT
                    echo "$changed_files"
                fi

            - name: Setup SHA
              id: generate_sha
              run: |
                echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

            - name: Login ghcr.io
              if: steps.backend_changes.outputs.changed_files != ''
              uses: docker/login-action@v2.1.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  logout: true

            - name: Build and Push to GitHub Container Registry
              if: steps.backend_changes.outputs.changed_files != ''
              uses: docker/build-push-action@v3.2.0
              with:
                  context: ./backend
                  tags: |
                      ghcr.io/chinathaip/bananagram/backend:${{ env.GITHUB_SHA }}
                  push: true

            - name: Image digest
              if: steps.backend_changes.outputs.changed_files != ''
              run: echo ${{ steps.docker_build.outputs.digest }}
