name: Backend CI/CD

on:
    push:
        branches: [main]

jobs:
    build-and-push:
        name: build and push docker image to ghcr
        permissions:
            packages: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Check for changed files in backend
              id: backend_changes
              run: |
                if git diff HEAD^ HEAD --quiet -- ./backend/src; then
                  echo "No changes in backend/src directory."
                  exit 0
                else
                  echo "Changes detected in backend/src directory."
                fi

            - name: Setup SHA
              run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

            - name: Login ghcr.io
              uses: docker/login-action@v2.1.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  logout: true

            - name: Build and Push to GitHub Container Registry
              uses: docker/build-push-action@v3.2.0
              with:
                  context: ./backend
                  tags: |
                      ghcr.io/chinathaip/bananagram/backend:${{ env.GITHUB_SHA }}
                  push: true

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}

    deploy-to-vm:
      name: Deploy new changes to VM
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Deploy new changes via SSH
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: |
              docker stop bananagram-be && docker rm banangram-be
              docker run --network=banangram --mount type=bind,source=./bananagram/.env,target=/usr/src/app/.env --name=bananagram-be -d ghcr.io/chinathaip/bananagram/backend:${GITHUB_SHA}
              docker image prune -a
